### ISSUE TITLE
Self-Organising Map

### ISSUE THREAD

**Issue by Thomio-Watanabe** [davidasboth/blog-notebooks#1]
I'm trying to run the Self-Organising Map.ipynb notebook but it is not grouping the input data.
Can you confirm the code is working ?
I tried to increase the number of iterations but still doesn't work.

**Comment by davidasboth** [comment]
Hi, the notebook looks fine to me, I've just tried it again. Are you trying it as is, or have you got another dataset you're trying it with?

**Comment by Thomio-Watanabe** [comment]
I'm running the code without modifications but I'm not running the jupyter notebook. I just copied the source code to a script. I'm attaching the result I get. I was expecting similar colors to be closer to each other, but only the black does. Is this right ?
![som](https://user-images.githubusercontent.com/7881475/31317444-b1470b9a-ac17-11e7-95a7-91a3d00f967a.png)

**Comment by davidasboth** [comment]
Hmm you're right, that doesn't look like a good result at all. Could you attach the script that produced that image? I'm interested in seeing what's going on here!

**Comment by Thomio-Watanabe** [comment]
I just forked this repo. Check [here](https://github.com/Thomio-Watanabe/blog-notebooks/blob/master/self-organising-map/test.py).

**Comment by davidasboth** [comment]
Hmm worked OK for me, I just ran the code as is, and got this. Apart from trying to increase the number of iterations I don't know what else to suggest! I presume you've tried it a few times, and get a similar negative result? Obviously there's an element of randomness that means each run is different, but they should all look like they're at least grouping similar colours together.

![figure_1](https://user-images.githubusercontent.com/10253275/31318125-e12f083a-ac44-11e7-9be4-8748c701c3b2.png)

**Comment by Thomio-Watanabe** [comment]
Thanks @davidasboth, it works with python3 on Ubuntu16.04.
It seems the problem is related to the classic python2 float point to int approximation.
To solve the problem you can add this `from __future__ import division` in the first line.

**Comment by davidasboth** [comment]
Good spot, thanks! Also a classic example of "works on my machine". Added the suggested future proofing.

**Comment by Thomio-Watanabe** [comment]
yw. By the way, you should "import division" in the first line. Like this:

    from __future__ import division
    import numpy as np
    from matplotlib import pyplot as plt
    from matplotlib import patches as patches

Otherwise python2 will display this error message (on ubuntu):

    SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by davidasboth** [comment]
Good to know, fixed. You can tell I'm a Python 3 user!
